require('plugins')
require('options')
require('keymaps')
require('gitsigns-config')
require('nvim-tree-config')
require('treesitter')
require('lsp')
require('lualine-config')
require('telescope-config')
require('completions')
require('lsp')
vim.cmd("colorscheme nightfox")
